### ISSUE TITLE
AL case bump

### ISSUE THREAD

**Issue by nmmarquez** [uclalawcovid19behindbars/historical-data#16]
It looks like for the week of 8-23-2020 for the state of AL we have a strange bump in cases. This wasnt present in the MP data time series. Worth checking out in the future.

![2021-04-08-101108_962x475_scrot](https://user-images.githubusercontent.com/5198764/114042518-8110c700-9853-11eb-8741-fd757549ed19.png)

**Comment by erika-tyagi** [comment]
Just adding that I think it's coming from the data from 2021-08-26 where it seems like a bunch of facilities have a spike!

<img width="571" alt="Screen Shot 2021-06-17 at 7 54 47 AM" src="https://user-images.githubusercontent.com/47676353/122400486-62106e80-cf41-11eb-940c-f9294298836f.png"> 
 <img width="562" alt="Screen Shot 2021-06-17 at 7 55 06 AM" src="https://user-images.githubusercontent.com/47676353/122400481-6046ab00-cf41-11eb-838c-5d15b2e8e01b.png">

**Comment by hjohns12** [comment]
Thanks for catching! Filtered out the problem date.
