### ISSUE TITLE
Kansas re-scrape 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#32]
It seems like something went awry in the Kansas historical data from 2020-10-07 to 2020-10-18 (started pulling from the new scrapers on 2020-10-20). Here's cumulative cases for incarcerated people and staff: 

<img width="400" alt="Screen Shot 2021-05-19 at 1 59 00 PM" src="https://user-images.githubusercontent.com/47676353/118868941-69911900-b8aa-11eb-8ad7-06b7dc032e64.png"> <img width="400" alt="Screen Shot 2021-05-19 at 1 59 07 PM" src="https://user-images.githubusercontent.com/47676353/118868953-6c8c0980-b8aa-11eb-9a81-7b11ad12aa18.png">

I think we should just drop the pre-November historical data for these days, and use the wayback pipeline instead to fill in this data. There's [really good wayback coverage](https://web.archive.org/web/20201201000000*/https://www.doc.ks.gov/kdoc-coronavirus-updates/kdoc-covid-19-status), and I just tested the pipeline out and it works really well here (yay for simple html tables).

**Comment by hjohns12** [comment]
Thanks for catching this! I went back to the pre-nov historical data cleaning script and filtered out those dates rather than just making `Residents.Confirmed` NA :0 Also changed it to all facilities rather than the 10/12 that were problematic so that the way back scrape is clean!
