### ISSUE TITLE
Washington late-Aug staff cases and tests data 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#34]
Some issues with staff data between 2020-08-17 and 2020-09-01 – the data we have isn't reflected in the wayback archives (e.g. from [2020-08-17](https://web.archive.org/web/20200817051458/https://www.doc.wa.gov/corrections/covid-19/data.htm), so I think we should replace our data with wayback scraped data for this set of days! 

<img width="400" alt="Screen Shot 2021-05-26 at 11 46 53 AM" src="https://user-images.githubusercontent.com/47676353/119699734-140fbb80-be18-11eb-9bd8-887ee65e6f9e.png"> <img width="400" alt="Screen Shot 2021-05-26 at 11 47 11 AM" src="https://user-images.githubusercontent.com/47676353/119699766-1d008d00-be18-11eb-91b9-151fa0c59da2.png">

**Comment by hjohns12** [comment]
Made the staff data for these dates `NA`!
