### ISSUE TITLE
Issue w/ Michigan deaths in October 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#43]
Seems like something went awry w/ `Residents.Deaths` in Michigan for a week in October for a few facilities: 
* MARQUETTE BRANCH PRISON has 561 deaths on 2020-10-20 and 457 on 2020-10-23
* IONIA CORRECTIONAL FACILTY has 159 deaths on 2020-10-23
* RICHARD A HANDLON CORRECTIONAL FACILITY has 52 deaths on 2020-10-20 and 64 on 2020-10-23

There have been 141 deaths in total across Michigan prisons, so these can't be right. 

If it's easiest, we also had the new scrapers up-and-running this week, so I think we could just filter out this week from the pre-November file.

**Comment by hjohns12** [comment]
Resolved and re-sent the file to the server. Ty for the helpful issue!
