### ISSUE TITLE
Alabama staff deaths 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#48]
From 2020-05-30 through 2020-06-25, `FOUNTAIN CORRECTIONAL FACILITY` shows 3 deaths for `Staff.Deaths`. in the data, but this should be 0 (there haven't been any staff deaths at the facility). 

<img width="500" alt="Screen Shot 2021-07-27 at 10 01 52 AM" src="https://user-images.githubusercontent.com/47676353/127167543-c0f11be6-7b09-459f-a681-25f0b30499ce.png">

**Comment by hjohns12** [comment]
Fixed in the script and updated server data. Thanks for catching this!
