### ISSUE TITLE
CDCR staff data (9/4-9/7) 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#51]
I think something went awry in the data collection for California staff from 9/4/2 - 9/7/20. Counts are much lower than wayback archive numbers for nearly all facilities (e.g. [here](https://web.archive.org/web/20200909074428/https://www.cdcr.ca.gov/covid19/cdcr-cchcs-covid-19-status/)). 

I think we can either delete these days of data or use the wayback pipeline to fill them in – whatever you think makes more sense!

**Comment by hjohns12** [comment]
Rm'd the data for those four days
