### ISSUE TITLE
Illinois 11/4/20 data 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#52]
There's data for Illinois in the pre-Nov file that doesn't seem to match the wayback archive [here](https://web.archive.org/web/20201104010352/https://www2.illinois.gov/idoc/facilities/Pages/Covid19Response.aspx) for 11/4/20. The new scraper is up and running at this point, so I think we can just remove the data for this date from the Illinois file!

**Comment by hjohns12** [comment]
Rm'd data for this date!
