### ISSUE TITLE
South Dakota issues 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#58]
A few facilities in South Dakota seem to be off on `2020-10-18` (e.g. `SOUTH DAKOTA WOMENS PRISON PIERRE` has 11 `Residents.Confirmed` when it should be 75. Can probably just delete this date (since we have data on 10/14 and 10/20). 

SIOUX FALLS COMMUNITY WORK CENTER is off on `2020-11-02` and `2020-11-04` (reporting 228 `Residents.Confirmed` when it should be around 116 (raw file [here](http://104.131.72.50:3838/scraper_data/raw_files/2020-11-03_south_dakota.pdf)). Can just delete and let the new scraper fill those values in!

**Comment by hjohns12** [comment]
fixed in pre-nov, ty!
