### ISSUE TITLE
North Carolina facilities 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/historical-data#60]
On `2020-11-04`, values for `TABOR CORRECTIONAL INSTITUTION` and `ALEXANDER CORRECTIONAL INSTITUTION` spike, but then fall the next day (raw file [here](http://104.131.72.50:3838/scraper_data/raw_files/2020-11-05_north_carolina.html), no WBM archive for that particular though). Can probably just delete these two facilities for `2020-11-04` though.

**Comment by hjohns12** [comment]
fiiiiixd it, thanks for finding!
